name: python
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Set up Python
      with:
        python-version: "3.7"
    - name: install
      run: |
        cd ${GITHUB_WORKSPACE}/scripts && ./devtools.sh
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Set up Python
      with:
        python-version: "3.7"
    - name: lint
      run: |
        cd ${GITHUB_WORKSPACE}/scripts && ./lint.sh
  package:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Set up Python
      with:
        python-version: "3.7"
    - name: package
      run: |
        cd ${GITHUB_WORKSPACE}/scripts && ./build.sh
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Set up Python
      with:
        python-version: "3.7"
    - name: test
      run: |
        cd ${GITHUB_WORKSPACE}/scripts && ./test.sh

